/**
 * 
 * Manages devices through Devicelink. 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DevicePropertiesStatusActions } from './devicePropertiesStatusActions';
import { DevicePropertiesStatusPredicate } from './devicePropertiesStatusPredicate';
import { DevicePropertiesStatusTopic } from './devicePropertiesStatusTopic';


export interface DevicePropertiesStatus { 
    topic?: DevicePropertiesStatusTopic;
    predicate?: DevicePropertiesStatusPredicate;
    actions?: DevicePropertiesStatusActions;
    status?: DevicePropertiesStatus.StatusEnum;
}
export namespace DevicePropertiesStatus {
    export type StatusEnum = 'acked' | 'unknown';
    export const StatusEnum = {
        Acked: 'acked' as StatusEnum,
        Unknown: 'unknown' as StatusEnum
    };
}
