/**
 * 
 * Manages devices through Devicelink. 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DevicePropertiesStatusPredicate { 
    operation?: DevicePropertiesStatusPredicate.OperationEnum;
    locked?: boolean;
    testPropertyIndex?: number;
    refValues?: Array<any>;
}
export namespace DevicePropertiesStatusPredicate {
    export type OperationEnum = 'match' | 'no_match' | 'equal' | 'more' | 'less' | 'between' | 'inherit' | 'is_present';
    export const OperationEnum = {
        Match: 'match' as OperationEnum,
        NoMatch: 'no_match' as OperationEnum,
        Equal: 'equal' as OperationEnum,
        More: 'more' as OperationEnum,
        Less: 'less' as OperationEnum,
        Between: 'between' as OperationEnum,
        Inherit: 'inherit' as OperationEnum,
        IsPresent: 'is_present' as OperationEnum
    };
}
