/**
 * 
 * Manages devices through Devicelink. 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DeviceInfoModelStream { 
    key?: number;
    readOnly?: boolean;
    time?: number;
    lastValue?: any;
}
