/**
 * 
 * Manages devices through Devicelink. 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DeviceInfoModel } from './deviceInfoModel';


export interface DeviceInfo { 
    time?: number;
    id?: number;
    model?: DeviceInfoModel;
    serialNumber?: string;
    firmware?: string;
    metadata?: any;
    activityout?: number;
    freshnessWindow?: number;
    lastRcv?: number;
    permissions?: DeviceInfo.PermissionsEnum;
}
export namespace DeviceInfo {
    export type PermissionsEnum = 'read_only' | 'write' | 'owner';
    export const PermissionsEnum = {
        ReadOnly: 'read_only' as PermissionsEnum,
        Write: 'write' as PermissionsEnum,
        Owner: 'owner' as PermissionsEnum
    };
}
