/**
 * 
 * Manages devices through Devicelink. 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GroupInfo { 
    time?: number;
    metadata?: any;
    devices?: Array<string>;
    permissions?: GroupInfo.PermissionsEnum;
}
export namespace GroupInfo {
    export type PermissionsEnum = 'read_only' | 'write' | 'owner';
    export const PermissionsEnum = {
        ReadOnly: 'read_only' as PermissionsEnum,
        Write: 'write' as PermissionsEnum,
        Owner: 'owner' as PermissionsEnum
    };
}
